name: "Bug report (General)"
description: "Report a problem not directly caused by OpenAPI input"
body:
  - type: markdown
    attributes:
      value: |
        Please search existing issues before filing a new one.

        Reproduction is required. If we cannot reproduce the issue, we will close it as needs-repro.

        If you suspect the OpenAPI document is part of the problem, use the "Bug report (OpenAPI/OAS)" template instead.
  - type: input
    id: orval_version
    attributes:
      label: "Orval version"
      placeholder: "e.g. 6.31.0"
    validations:
      required: true
  - type: input
    id: client
    attributes:
      label: "Client"
      description: "Which client are you using?"
      placeholder: "e.g. axios, fetch, react-query, angular, swr"
    validations:
      required: true
  - type: input
    id: output_mode
    attributes:
      label: "Output mode"
      description: "Your output mode setting."
      placeholder: "e.g. single, split, tags, tags-split"
    validations:
      required: true
  - type: dropdown
    id: custom_mutator
    attributes:
      label: "Custom mutator"
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: validator
    attributes:
      label: "Schema validation"
      options:
        - "None"
        - "zod"
        - "Other (specify in Additional context)"
        - "Not sure"
    validations:
      required: true
  - type: dropdown
    id: mocking
    attributes:
      label: "Mocking"
      options:
        - "None"
        - "msw"
        - "Other (specify in Additional context)"
        - "Not sure"
    validations:
      required: true
  - type: textarea
    id: search_terms
    attributes:
      label: "Search terms"
      description: "What did you search for before filing this issue?"
      placeholder: "e.g. react-query mutation types, generated types mismatch"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: "Reproduction steps"
      description: |
        Provide a minimal reproduction. This is required.
        Include a repo link or a minimal code snippet and clear steps to run it.
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior"
      description: "What should happen?"
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual behavior"
      description: "What actually happens?"
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: "Configuration"
      description: "Relevant generator config or options."
      value: |
        ```ts
        // config snippet
        ```
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      value: |
        - OS:
        - Node:
        - Package manager:
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: "Anything else that helps us reproduce or understand the issue."
    validations:
      required: false
