name: "Bug report"
description: "Report a problem so we can reproduce and fix it"
body:
  - type: markdown
    attributes:
      value: |
        Please search existing issues before filing a new one.

        Reproduction is required. If we cannot reproduce the issue, we will close it as needs-repro.

        If this is OpenAPI-related, validate your spec at https://editor.swagger.io and include the results.
  - type: textarea
    id: config_ts
    attributes:
      label: "Configuration (config.ts)"
      description: "Paste your full config.ts here."
      value: |
        ```ts
        // paste your config.ts here
        ```
    validations:
      required: true
  - type: textarea
    id: search_terms
    attributes:
      label: "Search terms"
      description: "What did you search for before filing this issue?"
      placeholder: "e.g. react-query mutation types, openapi_31 validation error"
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior"
      description: "What should happen?"
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual behavior"
      description: "What actually happens?"
    validations:
      required: true
  - type: textarea
    id: openapi_version
    attributes:
      label: "OpenAPI version (if applicable)"
      placeholder: "e.g. 3.0.3 or 3.1.0"
    validations:
      required: false
  - type: textarea
    id: openapi_document
    attributes:
      label: "OpenAPI document (minimal, if applicable)"
      description: |
        If OpenAPI-related, provide the smallest possible OpenAPI document that reproduces the issue.
        Paste YAML/JSON or link to a public repo/file.
      value: |
        ```yaml
        openapi: 3.0.3
        info:
          title: Demo
          version: 0.0.0
        paths: {}
        ```
    validations:
      required: false
  - type: textarea
    id: swagger_validation
    attributes:
      label: "Swagger Editor validation (if applicable)"
      description: |
        If OpenAPI-related, validate the spec at https://editor.swagger.io and paste the results.
        Include errors, warnings, and any link or screenshot.
      placeholder: |
        - Errors:
        - Warnings:
        - Link or screenshot:
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      value: |
        - OS:
        - Node:
        - Package manager:
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: "Anything else that helps us reproduce or understand the issue."
    validations:
      required: false
