name: "Bug report"
description: "Report a problem so we can reproduce and fix it"
body:
  - type: markdown
    attributes:
      value: |
        Please search existing issues before filing a new one.

        Reproduction is required. If we cannot reproduce the issue, we will close it as needs-repro.

        If this is OpenAPI-related, validate your spec at https://editor.swagger.io and include the results.
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the issue briefly."
      placeholder: "e.g. react-query mutation types, openapi_31 validation error"
    validations:
      required: true
  - type: textarea
    id: config_file
    attributes:
      label: "Configuration (orval.config)"
      description: "Paste your full orval.config file here."
      value: |
        ```ts
        // paste your orval.config file here
        ```
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior"
      description: "What should happen?"
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual behavior"
      description: "What actually happens?"
    validations:
      required: true
  - type: textarea
    id: openapi_document
    attributes:
      label: "OpenAPI document (minimal, if applicable)"
      description: |
        If OpenAPI-related, provide the smallest possible OpenAPI document that reproduces the issue.
        Validate at https://editor.swagger.io, then paste the spec here (YAML/JSON) or link to a public repo/file.
      value: |
        ```yaml
        openapi: 3.0.3
        info:
          title: Demo
          version: 0.0.0
        paths: {}
        ```
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: "Anything else that helps us reproduce or understand the issue."
    validations:
      required: false
